<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.InvocationTimeOut.InvocationTimeOut" tests="1" time="0.025" ignored="0" failures="0" timestamp="18 Apr 2020 09:32:29 GMT" skipped="0" hostname="Nayem" errors="1">
  <testcase name="infiniteLoopTest" time="0.025" classname="com.InvocationTimeOut.InvocationTimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.InvocationTimeOut.InvocationTimeOut.infiniteLoopTest() didn&#039;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.InvocationTimeOut.InvocationTimeOut.infiniteLoopTest() didn't finish within the time-out 1
	at java.lang.System.arraycopy(Native Method)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
	at sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)
	at java.io.OutputStreamWriter.flushBuffer(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at java.io.PrintStream.print(Unknown Source)
	at java.io.PrintStream.println(Unknown Source)
	at com.InvocationTimeOut.InvocationTimeOut.infiniteLoopTest(InvocationTimeOut.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- infiniteLoopTest -->
</testsuite> <!-- com.InvocationTimeOut.InvocationTimeOut -->
